# Uncomment the next line to define a global platform for your project
platform :ios, '12.3'

source 'https://cdn.cocoapods.org/'
source 'https://github.com/Mapsted/podspec.git'

use_frameworks!
target 'Sample' do
  
end
target 'Sample_MapOnly' do
  
end
