# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

source 'https://cdn.cocoapods.org/'
source 'https://github.com/Mapsted/podspec.git'

use_frameworks!

target 'Sample' do
  pod 'mapsted-sdk-map-ui', '~> 4.6.5'
end
target 'Sample_MapOnly' do
  pod 'mapsted-sdk-map', '~> 4.6.5'
end
